Transform: AWS::Serverless-2016-10-31

Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Handler: LTExercise::LTExercise.LambdaHandler::FunctionHandlerAsync
      CodeUri: src/bin/Release/net6.0/src.zip
      Runtime: dotnet6
      MemorySize: 512
      Timeout: 20
      AutoPublishAlias: live
      Events:
        Api:
          Type: HttpApi
          Properties:
            TimeoutInMillis: 20000

Outputs:
  ApiUrl:
    Value: !Sub https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com
  Function:
    Value: !Ref Function